Symplectic C5
gap-packages/ClassicalMaximals pull request #75
Opened 2021-10-31 14:21 UTC by TristanPfersdorff

Add the necessary functions for the C5 subgroups in the symplectic case. The codecov bot will be happy once we add the symplectic main function.

## Checklist for the reviewer
### General
- [ ] All functions have unit tests

### Functions constructing generators of maximal subgroups
- [ ] The code which computes and then stores the sizes is correct. To do this one confers to the tables referenced by the code. Tests for the group size should use `RECOG.TestGroup` from the recog package.
- [ ] The test suite checks whether all constructed generators are sensible. That is it tests the generators'
  - [ ] determinants (and if applicable also the spinor norms are correct), and
  - [ ] compatibility with the correct form,
  - [ ] `DefaultFieldOfMatrixGroup` returns the correct field.

### Functions assembling the list of all maximal subgroups of a certain group
- [ ] The code agrees with the tables in section 8.2 of the book "The Maximal Subgroups of the Low-dimensional Finite Classical Groups".

The reviewer doesn't need to compare our results to magma's results. That's the job of the person implementing the code.

2021-10-31 22:46 UTC, maxhauck commented on gap/ClassicalMaximals.gi
> +    return List(PrimeDivisors(e), b -> SubfieldSp(n, p, e, QuoInt(e ,b)));
You have to remember conjugating the subgroup you constructed by an element of GSp \ Sp in order to get all the conjugacy classes in Sp, see for example ll. 833-834 at https://github.com/hulpke/maxtrans/blob/master/magma/classmax.m

2021-11-03 12:40 UTC, fingolfin reviewed
Some suggestions. Overall looks fine to me, modulo the remark by @maxhauck

2021-11-03 12:40 UTC, fingolfin commented on gap/SubfieldMatrixGroups.gi
> +    fi;
In general I'd try move input validation to the very start, before any work is done. Also, this checks for two conditions, and so I'd suggest to have two errors; that makes it slightly easier for a human to understand what's going on. I.e., together with what I wrote above:
```suggestion
    if e mod f <> 0 then
        ErrorNoReturn("<f> must be a divisor of <e>");
    fi;
    if not IsPrime(b) then
        ErrorNoReturn("The quotient of <f> by <e> must be a prime");
    fi;
```

2021-11-03 12:40 UTC, fingolfin commented on gap/SubfieldMatrixGroups.gi
> +    C := DiagonalMat(Concatenation(List([1..l], i -> omega * zetaPower), List([1..l], i -> zetaPower)));
```suggestion
    C := DiagonalMat(Concatenation(ListWithIdenticalEntries(l, omega * zetaPower), ListWithIdenticalEntries(l, zetaPower)));
```

2021-11-03 17:11 UTC, TristanPfersdorff commented
The proposed changes seem good to me, I have implemented them and rebased. As for the remark by @maxhauck, it seems like it suffices to call `ConjugatesInGeneralGroup` with his function `NormSpMinusSp` from the C6-PR (#74) in the right spot once that PR has been merged (maybe one could do some fancy git-stuff with this PR depending on #74, but I'm no expert).
I still don't really know what to make of that weird RECOG-error (`Error, Matrix INV: <mat> must be square (not 2 by 4)`); It seems to happen somewhat frequently when the test run for the first time, but it rarely occurs when re-running the tests (without reloading the package). I've encountered it a couple times now but I can't seem to make sense of it, since every matrix we use is square.

2021-11-10 14:25 UTC, fingolfin approved these changes

2021-11-10 14:27 UTC, fingolfin requested changes
As with PR #74 this now has a conflict in `gap/ClassicalMaximals.gi` so this PR here can't be merged; also once PR #74 is merged we may have a fresh conflict. So yeah, perhaps move the C1/C2/... cases into separate files?

Also, tests are failing, that needs to be resolved first (I overlooked that).

2021-11-10 14:27 UTC, fingolfin commented on tst/standard/SubfieldMatrixGroups.tst
> +gap> SubfieldSp(3, 2, 2, 1);
I would suggest to add a comment that explains error handling is being tested (as opposed to a broken test file)
```suggestion

# test error handling
gap> SubfieldSp(3, 2, 2, 1);
```

2021-11-18 09:06 UTC, merged