Revise some error messages
gap-packages/ClassicalMaximals pull request #83
Opened 2021-11-19 16:23 UTC by fingolfin

- Don't use trailing period
- Don't print values; the user can print them if they want to via the break loop
- Be more consistent in how errors are worded (more to be done)

2021-11-19 16:38 UTC, maxhauck approved these changes
Duly noted!

2021-11-19 19:41 UTC, TristanPfersdorff requested changes
Looks good, I'll be sticking to these conventions in the future. Just found a tiny imperfection :)

2021-11-19 19:41 UTC, TristanPfersdorff commented on gap/ExtraspecialNormalizerMatrixGroups.gi
> +                      "unitary case,");
```suggestion
                      "unitary case");
```

2021-11-19 19:41 UTC, TristanPfersdorff commented on gap/ExtraspecialNormalizerMatrixGroups.gi
> +        ErrorNoReturn("<r> ^ <m> must be at least 2 in the unitary case,");
```suggestion
        ErrorNoReturn("<r> ^ <m> must be at least 2 in the unitary case");
```

2021-11-26 13:17 UTC, TristanPfersdorff approved these changes

2021-11-26 13:57 UTC, merged